"""Test 11: Template-optional path (Phase 2/3).

Verifies the new style-driven DOCX generation:
  * Caller does NOT set use_legacy_template → style-driven path is used
  * The pipeline produces a DOCX even when no template is relevant
  * The DOCX has explicit RTL formatting (bidi + rtl)
  * The DOCX has no [source:] tags and no ## المصادر section
  * The DOCX has the standard Saudi administrative letter skeleton
    (date row, Basmala, recipient block, body, closing, signature)
  * The persisted draft has template_* = NULL (no template was used)
  * The compliance reviewer accepts a well-formed دعوة-style letter
"""
from __future__ import annotations
import os
import sys
import io
import json
import zipfile
import re

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from tests.acceptance.framework import api_post, run_test, TestResult, _supabase


DESCRIPTION = (
    "A request for an invitation letter should be generated by the "
    "style-driven path (no template required) and produce a clean, "
    "well-formed, official-looking Arabic RTL DOCX."
)
EXPECTED = (
    "intent=general_assembly_invitation, docx produced, no [source:] in DOCX, "
    "no ## المصادر in DOCX, <w:bidi/> on every paragraph, persisted draft "
    "has template_document_id/file_id/version = NULL."
)


def _check_docx_formatting(docx_bytes: bytes, r: TestResult) -> dict:
    """Inspect a generated DOCX; return stats for the test runner."""
    with zipfile.ZipFile(io.BytesIO(docx_bytes)) as zf:
        xml = zf.read("word/document.xml").decode("utf-8", errors="replace")

    # All paragraphs
    paras = re.findall(r"<w:p[\s>].*?</w:p>", xml, flags=re.DOTALL)
    bidi_count = sum(1 for p in paras if "<w:bidi" in p)
    rtl_count  = sum(1 for p in paras if "<w:rtl" in p)

    has_source_tag = "[source:" in xml
    has_masader    = "## المصادر" in xml

    # Extract all text
    all_text = "".join(re.findall(r"<w:t[^>]*>([^<]*)</w:t>", xml))

    return {
        "paragraphs":      len(paras),
        "bidi_paragraphs": bidi_count,
        "rtl_paragraphs":  rtl_count,
        "has_source_tag":  has_source_tag,
        "has_masader":     has_masader,
        "all_text_len":    len(all_text),
    }


def run(r: TestResult) -> None:
    body = {
        "request": "اكتب لي خطابًا رسميًا لدعوة أعضاء الجمعية العمومية لحضور اجتماع الجمعية العمومية",
        "fields": {},
        # Do NOT set use_legacy_template — the style-driven path is the
        # production default. This test asserts that the new path works
        # end-to-end.
    }
    res = api_post("/letters/generate", body, timeout=300.0)

    # 1) Intent is general_assembly_invitation (the new system still
    #    uses intent detection — it's the export path that changed).
    intent = res.get("intent") or {}
    intent_type = intent.get("letter_type")
    r.add_finding("info", f"intent detected: {intent_type} (conf={intent.get('confidence', 0):.2f})")
    assert intent_type == "general_assembly_invitation", (
        f"intent was {intent_type!r}, expected general_assembly_invitation"
    )

    # 2) A DOCX was produced.
    docx_url = res.get("docx_url")
    assert docx_url, "no docx_url returned"
    r.add_finding("info", f"DOCX URL: {docx_url[:120]}")

    # 3) The result does NOT advertise a template (template_profile is None).
    tp = res.get("template_profile")
    assert tp is None, f"expected template_profile=None for style-driven path, got {tp!r}"
    r.add_finding("info", "template_profile=None (style-driven path)")

    # 4) The stages trace shows the style-driven export.
    stages = res.get("stages") or []
    export_stage = next((s for s in stages if s.get("stage") == "export"), None)
    assert export_stage, "no export stage in trace"
    note = export_stage.get("note") or ""
    assert "mode=style" in note, f"export stage note does not show mode=style: {note!r}"
    r.add_finding("info", f"export stage: {note[:160]}")

    # 5) Download the DOCX and inspect its formatting.
    import httpx
    HEADERS = {"X-Admin-Token": os.environ.get("ADMIN_TOKEN", "dev")}
    with httpx.Client(timeout=60.0, headers=HEADERS) as c:
        # The docx_url is a signed Supabase Storage URL; use it as-is.
        dres = c.get(docx_url)
    assert dres.status_code == 200, f"DOCX download failed: HTTP {dres.status_code}"
    docx_bytes = dres.content
    r.add_finding("info", f"DOCX downloaded: {len(docx_bytes)} bytes")

    stats = _check_docx_formatting(docx_bytes, r)
    r.add_finding("info", f"formatting: {stats}")

    # 6) The DOCX must have explicit RTL formatting on every paragraph.
    assert stats["bidi_paragraphs"] == stats["paragraphs"], (
        f"only {stats['bidi_paragraphs']}/{stats['paragraphs']} paragraphs have <w:bidi/>"
    )
    assert stats["rtl_paragraphs"] >= 1, (
        f"no paragraphs have <w:rtl/> tag — RTL not applied to runs"
    )

    # 7) The DOCX must NOT have citation tags or المصادر section.
    assert not stats["has_source_tag"], "DOCX contains [source:] tags — must be clean"
    assert not stats["has_masader"], "DOCX contains ## المصادر section — must be clean"

    # 8) The persisted draft has template_* = NULL.
    draft_id = res.get("draft_id")
    assert draft_id, "no draft_id returned"
    sb = _supabase()
    dres = sb.table("drafts").select(
        "template_document_id,template_file_id,template_version"
    ).eq("id", draft_id).limit(1).execute()
    assert dres.data, f"draft {draft_id} not found in DB"
    drow = dres.data[0]
    r.add_finding("info", f"persisted template_document_id={drow['template_document_id']}")
    assert drow["template_document_id"] is None, (
        f"template_document_id should be NULL, got {drow['template_document_id']!r}"
    )
    assert drow["template_file_id"] is None, (
        f"template_file_id should be NULL, got {drow['template_file_id']!r}"
    )
    assert drow["template_version"] is None, (
        f"template_version should be NULL, got {drow['template_version']!r}"
    )

    # 9) The final_status is one of the acceptable outcomes (ok / fixable / needs_review).
    final_status = res.get("final_status")
    assert final_status in ("ok", "fixable", "needs_review"), (
        f"final_status was {final_status!r}, expected ok/fixable/needs_review"
    )
    r.add_finding("info", f"final_status: {final_status}")


def test():
    return run_test(
        name="11_template_optional",
        description=DESCRIPTION,
        expected=EXPECTED,
        fn=run,
    )
